#!/usr/bin/env php
<?php

if (\file_exists(__DIR__ . '/vendor/autoload.php')) {
    require_once __DIR__ . '/vendor/autoload.php';
} else {
    require_once __DIR__ . '/../../autoload.php';
}

ini_set('memory_limit', '-1');
ini_set('xdebug.max_nesting_level', '10000');

require_once __DIR__ . '/main.php';

JesseSchalken\AutoloadGenerator\Generator::main($_SERVER['argv']);

